module.exports.emoji = require('./src/findtheemoji')
module.exports.audit = require('./src/audit')
module.exports.createsticker = require('./src/sticker')
module.exports.avatar = require('./src/advancedav')
module.exports.starter = require('./src/starter')