module.exports.emoji = require('./src/findtheemoji')
module.exports.audit = require('./src/audit')
module.exports.createsticker = require('./src/sticker')
module.exports.avatar = require('./src/advancedav')
module.exports.starter = require('./src/starter')
module.exports.afk = require('./src/afk')
module.exports.loop = require('./src/loop')
module.exports.shotoniphone = require('./src/iphone')